### PR TITLE
Added meta title to following page

### PR DESCRIPTION
**Pull request by askvortsov1**

### CODE REVIEW

**Comment by dsevillamartin** [comment]
Is there any reason as to why this code is going in `config` instead of `init`? Looks like we put `app.setTitle()` calls in the `init` method in core.

**Comment by askvortsov1** [comment]
> Is there any reason as to why this code is going in `config` instead of `init`? Looks like we put `app.setTitle()` calls in the `init` method in core.

I don't think we do: https://github.com/flarum/core/blob/0d208dc4437c0cc551c556d2c2cc7c12bda369ae/js/src/forum/components/IndexPage.js#L98

**Comment by dsevillamartin** [comment]
Ah, looks like we put it in either (https://github.com/flarum/core/blob/68afdd21aee3b2032aaf89052bf3951c164df01d/js/src/forum/components/SettingsPage.js#L16-L21).

**Comment by askvortsov1** [comment]
I'm seeing that sometimes it's also in show. Should we standardize the location?

**Comment by dsevillamartin** [comment]
@askvortsov1 Show is called from `init` I think, or outside calls.

**Comment by askvortsov1** [comment]
Should we standardize the location? I'm not too familiar with frontend convention

**Review by franzliedke — CHANGES_REQUESTED** [review]
Please review our [documentation about standard key format](https://flarum.org/docs/extend/i18n.html#appendix-a-standard-key-format) and change the key accordingly. 

[My change here](https://github.com/flarum/lang-english/commit/bd722e41b3448e07e61856e05b0481ddcad40625) may serve as inspiration.

**Comment by askvortsov1** [comment]
> Please review our [documentation about standard key format](https://flarum.org/docs/extend/i18n.html#appendix-a-standard-key-format) and change the key accordingly.
> 
> [My change here](https://github.com/flarum/lang-english/commit/bd722e41b3448e07e61856e05b0481ddcad40625) may serve as inspiration.

Done, thanks!

**Review by franzliedke — APPROVED** [review]

**Pull request merged**
