### PR TITLE
Added event when searching subscirbed discussions, for extensibility.

### PR DESCRIPTION
**Pull request by iPurpl3x**
I used this in a case that I have mentioned here : https://github.com/flarum/core/issues/2306

I may have added more stuff than needed to the fired event. If I should make it slimmer just let me know.

### CODE REVIEW

**Comment by askvortsov1** [comment]
Seeing as we're currently trying to move away from these events to extenders, I'm not sure I like introducing new ones here.

**Comment by iPurpl3x** [comment]
@askvortsov1 I understand, so what's the alternative solution to extend this ?

**Comment by askvortsov1** [comment]
Personally, I'd like to avoid extensibility within gambits; instead, imo additional gambits should be applied (or replaced, that might be better for your use case). That should become more feasible as we introduce gambit extenders in https://github.com/flarum/core/pull/2104/files

**Comment by iPurpl3x** [comment]
@askvortsov1 In my case adding another Gambit didn't work, it simply had no effect. So I would have to replace the original `SubscriptionGambit`. Which works, but isn't a clean solution IMO...

**Comment by askvortsov1** [comment]
I agree it's not ideal, but I also don't think that arbitrarily adding events into gambits is a path we want to take for core. Perhaps if there was some way to add an extender for ALL gambits?

**Comment by iPurpl3x** [comment]
OK today I found another way around my initial issue. And I don't need the custom event that I created here anymore so I will close this PR. 

FYI: I found out that when the frontend sends a request to the API, you can add multiple references of the same gambit pattern into the the same query and that would make that the changes that this gambit add to the search query are added on multiple places in the SQL query that gets generated. Example : `filter[q] = is:following is:review is:following-tag is:review is:following-users is:review`. Here I reuse the `is:review` multiple time so that it gets applied to each part of the SQL query where it filters for following discussions... I hope this is understandable! I can give more details if anyone is interested.

**Pull request closed without merging**
