### PR TITLE
Follow new discussions

### PR DESCRIPTION
**Pull request by oscarotero**
Hi!
Here I am again, after #9 🖖 

I've trying to re-implement the FollowNewDiscussion option in the new version of the plugin (I'm using this feature and cannot update flarum to the latest version until this is available).

If you're still interested in this feature, I'd be happy to do any change. If not, could you help me to make it work fine, please?

I'd like to filter the users to select only those than can see the new discussion, so I use `$post->isVisibleTo($user)`, but this does not return the right users. What would be the good way to do it?

Thanks!

### CODE REVIEW

**Review by franzliedke — COMMENTED** [review]
Welcome back, and thanks for pushing this forward!!!

Good news: since flarum/core#1773 was merged, we now have queueing support. Because this would potentially send a *lot* of emails, this feature must be executed on a queue.

Right now, we only have the infrastructure and no use-case yet. If you're interested in trying how to make that work, feel free to do so. Alternatively, you could wait for flarum/core#1869, which will be tackled for the next beta.

What do you think?

**Review by franzliedke — CHANGES_REQUESTED** [review]
Please don't commit changes to dist files. They will be automatically recompiled when this reaches the master branch. :smile:

**Comment by oscarotero** [comment]
Ok, thanks!

My main concern is how to make this work combined with other plugins in terms of permissions. I had to code a dirty fix for my forum that you can see here:
https://github.com/oscarotero/subscriptions/blob/foro-dag/src/Listener/FollowNewDiscussions.php

We have tags that are only visible for some user groups, so the notifications should be sent only for these users that can view these tags.

This is only a quick and dirty fix for my use case, I'd rather that anyone more familiarized with the core of Flarum (and Laravel framework) could add this feature properly 😃

**Comment by dsevillamartin** [comment]
Oh, we definitely want to check if the user can view the discussion first then. Could also be a private discussion (e.g. byobu), so we need to make sure to do that.

**Comment by franzliedke** [comment]
Closing, see https://github.com/flarum/core/issues/768#issuecomment-554558814.

**Pull request closed without merging**
