### PR TITLE
Repo maintenance: add Prettier config, update deps

### PR DESCRIPTION
**Pull request by davwheat**
- Updates deps
- Adds prettier
- Copy prettier config from core

### CODE REVIEW

**Comment by askvortsov1** [comment]
Could we add this to flarum CLI as an infra task, and then run that?

Also, can core's prettier config be extracted to its own package?

**Comment by davwheat** [comment]
I didn't think so, but yes! https://prettier.io/docs/en/configuration.html#sharing-configurations

**Review by SychO9 — APPROVED** [review]

**Comment by dsevillamartin** [comment]
May want to remember to extract prettier config into its own package.

**Comment by davwheat** [comment]
Yeah, I keep forgetting. If someone makes the repo (no perms), I'll get on it tonight.

**Review by tankerkiller125 — APPROVED** [review]

**Pull request merged**
