### PR TITLE
Fix .SubscriptionMenu-button--follow colors for dark mode

### PR DESCRIPTION
**Pull request by hasan-ozbey**
Button

I'm open to different color combinations.

### CODE REVIEW

**Review by askvortsov1 — APPROVED** [review]
Ah that's much better, thanks a lot! Looks good to me!

**Review by tankerkiller125 — APPROVED** [review]
Looks a lot better to me as well

**Comment by franzliedke** [comment]
@the-turk Thanks for the PR!

Where did these colors come from, by the way? Are they already used somewhere else? I'd prefer if we had a list of variables somewhere, to ensure consistency and avoid magic numbers.

**Comment by hasan-ozbey** [comment]
@franzliedke they're coming from nowhere, just like the original color codes (colors that you see before this PR).

**Pull request merged**
